add_newline = true
command_timeout = 200
format = """
[░▒▓](#F087BD)\
[ \ue712 ](bg:#F087BD fg:#1B1E28)\
[](bg:#FFFAC2 fg:#F087BD)\
$directory\
[](fg:#FFFAC2 bg:#5DE4C7)\
$git_branch\
$git_status\
[](fg:#5DE4C7 bg:#89DDFF)\
$time\
[](fg:#89DDFF bg:transparent)\
\n$character"""

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[time]
disabled = false
time_format = "%R"
style = "bold bg:#89DDFF"
format = '[[  $time ](fg:#1B1E28 bg:#89DDFF)]($style)'

[directory]
style = "fg:#1B1E28 bg:#FFFAC2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = "\ueafe"
style = "bold bg:#5DE4C7"
format = '[[ $symbol $branch ](fg:#303340 bg:#5DE4C7)]($style)'


[git_status]
format = '[[($all_status$ahead_behind )](fg:#303340 bg:#5DE4C7)]($style)'
style = "bold bg:#5DE4C7"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[nodejs]
symbol = ""
style = "bg:#1B212E"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#1B212E)]($style)'

[rust]
symbol = ""
style = "bg:#1B212E"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#1B212E)]($style)'

[golang]
symbol = ""
style = "bg:#1B212E"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#1B212E)]($style)'

[php]
symbol = ""
style = "bg:#1B212E"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#1B212E)]($style)'
